[package]
name = "guardian"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
concordium_governance_committee_election = { path = "../../../contracts/concordium-governance-committee-election", features = [ "serde", ] }
eg = { path = "../../../deps/electionguard-rust/src/eg" }
util = { path = "../../../deps/electionguard-rust/src/util" }
tauri = { version = "1.5", features = [
  "fs-read-dir",
  "fs-exists",
  "fs-write-file",
  "fs-read-file",
  "shell-open",
  "cli"
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
concordium-rust-sdk = "6.0"
rand = "0.8"
thiserror = "1.0"
election-common = { path = "../../../election-common" }
tokio = { version = "1.35", features = ["rt-multi-thread", "macros", "sync"] }
tonic = { version = "0.10", features = ["tls-roots"] }
anyhow = "1.0"
reqwest = { version = "0.11", features = ["json"] }
strum = { version = "0.26", features = ["derive"] }
itertools = "0.12"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
