[package]
name = "guardian"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
eg = {path = "../../../deps/electionguard-rust/src/eg"}
util = {path = "../../../deps/electionguard-rust/src/util"}
tauri = { version = "1.5", features = [ "fs-read-dir", "fs-exists", "fs-write-file", "fs-read-file", "shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
concordium-rust-sdk = {path = "../../../deps/concordium-rust-smart-contracts/concordium-rust-sdk"}
rand = "0.8"
thiserror = "1.0"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
