[package]
name = "election-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
axum = "0.7"
chrono = "0.4"
clap = { version = "4.4", features = ["derive", "env"] }
concordium-rust-sdk = "3.2"
concordium_governance_committee_election = { version = "0.1.0", path = "../contracts/concordium-governance-committee-election", features = ["full"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.50"
tokio = { version = "1.34", features = ["rt-multi-thread", "signal"]}
tokio-postgres = { version = "0.7", features = ["with-serde_json-1", "with-chrono-0_4"]}
tonic = {version = "0.10", features = ["tls", "tls-roots"]} # Use system trust roots.
tower-http = {version = "0.5", features = [
  "trace",
  "limit",
  "cors",
  "timeout",
]}
tracing = "0.1"
tracing-subscriber = "0.3"
