[package]
name = "election-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = "0.4"
clap = { version = "4.4", features = ["derive", "env"] }
concordium-rust-sdk = "3.2"
futures = "0.3"
tokio = { version = "1.34", features = ["rt-multi-thread", "signal"]}
tokio-postgres = "0.7"
tonic = {version = "0.10", features = ["tls", "tls-roots"]} # Use system trust roots.
