[package]
name = "election-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concordium-rust-sdk = { path = "../deps/concordium-rust-smart-contracts/concordium-rust-sdk/", optional = true }
rmp-serde = "1.1"
serde = {version = "1.0", features = ["derive"]}

[features]
default = ["full"]
full = ["dep:concordium-rust-sdk"]
