on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - contracts/**/*

name: check crates

env:
  RUST_FMT: nightly-2023-04-01
  RUST_VERSION: "1.67"
  CARGO_CONCORDIUM_VERSION: "3.0.0"

jobs:
  rustfmt:
    name: format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crates:
          - contracts/concordium-governance-committee-election/Cargo.toml

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install nightly toolchain with rustfmt available
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_FMT }}
          override: true
          components: rustfmt

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path=${{ matrix.crates }} -- --check

  test-contracts:
    name: test contracts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        contracts:
          - contracts/concordium-governance-committee-election

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true

      - name: Install Wasm target
        run: rustup target install wasm32-unknown-unknown

      - name: Download and install Cargo Concordium
        run: |
          CARGO_CCD=cargo-concordium_${{ env.CARGO_CONCORDIUM_VERSION }}
          wget https://distribution.concordium.software/tools/linux/$CARGO_CCD
          chmod +x $CARGO_CCD
          sudo mv $CARGO_CCD /usr/bin/cargo-concordium

      - name: Run cargo concordium test
        run: cargo concordium test --out "${{ matrix.contracts }}/concordium-out/module.wasm.v1" -- --manifest-path "${{ matrix.contracts }}/Cargo.toml"
