name: 'Publish Guardian App'
on:
  # push:
  #   branches:
  #     - release

  workflow_dispatch: # allows manual trigger from main
    inputs:
      contract:
        description: 'The election contract address in the format <index,subindex> (no spaces).'
        required: true
        type: string
      network:
        required: true
        type: choice
        description: 'Network for which this is built. Determines the node connection.'
        options:
          - testnet
          - mainnet
env:
  # The following environment variables need to be set for build to succeed.
  CCD_ELECTION_NODE: ${{ github.event.inputs.network == 'testnet' && 'https://grpc.testnet.concordium.com:20000' || 'https://grpc.mainnet.concordium.software:20000' }}
  CCD_ELECTION_CONTRACT_ADDRESS: ${{ github.event.inputs.contract }}
  CCD_ELECTION_NETWORK: ${{ github.event.inputs.network }} # e.g. "testnet", shown in the frontend of the app

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        settings:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin' # for Arm based macs (M1 and above).
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin' # for Intel based macs.
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.settings.platform }}
    steps:
      - name: Support longpaths on Windows
        if: matrix.settings.platform == 'windows-latest'
        run: git config --system core.longpaths true
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.settings.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      - name: install dependencies (ubuntu only)
        if: matrix.settings.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: install frontend dependencies & generate config
        working-directory: ./apps/guardian
        run: yarn install && yarn generate-config
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: 'apps/guardian'
          tauriScript: 'yarn tauri'
          args: '--config ./tauri-temp.conf.json ${{matrix.settings.args}}'
          tagName: release/guardian-app/v__VERSION__-${{ github.event.inputs.network }}-${{ github.event.inputs.contract }} # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: ${{ format('Guardian App v__VERSION__ for {0} ({1})', github.event.inputs.contract, github.event.inputs.network) }}
          releaseBody: 'See attached assets.'
          releaseDraft: true
          prerelease: false
